### ISSUE TITLE
shinydashboard => example_1 (by Kevin)

### ISSUE THREAD

**Issue by greedythib** [greedythib/R-Shiny-#3]
il faudrait que tu détailles dans le read_me de ce dossier les spécifités de l'example_1 (le code que tu avais mis dans le dossier shinydashboard) 
je le ferai également pour l'example_2 que je vais importer d'ici quelques heures

**Comment by kekevuvu** [comment]
Ok mais c'est pas trop une issue ni un tchat.

**Comment by greedythib** [comment]
si c'était une issue
